version: '3.9'

services:
  # Database for AuthGate
  tripa-db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db-data:
