version: '3.9'

services:
  # Database used for integration tests
  test-db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    volumes:
      - test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

volumes:
  test-data: